curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data2.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data2.json
curl -H "Content-type: application/json" -XPOST 'http://localhost:8080/items' -d @test_data2.json